/*------Question 14------*/
SELECT OWNER.NAME, OWNER.PhoneNumber
FROM OWNER, HANGAR, OWNS
WHERE OWNER.ID = OWNS.OWNER_ID
AND OWNER.Type = 'Company'
AND HANGAR.Number = OWNS.AIRPLANE_RegNum
AND HANGAR.LOCATION = OWNER.ADDRESS