/*------Question 15------*/
SELECT DISTINCT p.Name
FROM PERSON p
JOIN FLIES f ON f.PILOT_ID = p.ID
JOIN AIRPLANE a ON a.OF_TYPE = f.PLANE_TYPE_Model
JOIN MAINTAIN m ON m.SERVICE_ID = a.Reg#
WHERE a.STORED_IN = (SELECT Number FROM HANGAR WHERE Number = a.STORED_IN) AND TYPE='PILOT';

