/*------Question 16------*/
SELECT EMPLOYEE.Name, SUM(SERVICE.Hours) AS total_hours
FROM EMPLOYEE
JOIN MAINTAIN ON EMPLOYEE.ID = MAINTAIN.EMPLOYEE_ID
JOIN SERVICE ON MAINTAIN.SERVICE_ID = SERVICE.ID
JOIN AIRPLANE ON AIRPLANE.Reg# = SERVICE.ID
JOIN OWNS ON AIRPLANE.Reg# = OWNS.AIRPLANE_RegNum
JOIN OWNER ON OWNS.OWNER_ID = OWNER.ID AND OWNER.Name = 'John Smith'
GROUP BY EMPLOYEE.Name
ORDER BY total_hours DESC;