/*------Question 18------*/
SELECT DISTINCT O.Name, O.Address
FROM OWNER O
INNER JOIN OWNS OW ON O.ID = OW.OWNER_ID
INNER JOIN AIRPLANE A ON OW.AIRPLANE_RegNum = A.Reg#
INNER JOIN PLANE_TYPE PT ON A.OF_TYPE = PT.Model
INNER JOIN CORPORATION C ON C.ID = OW.OWNER_ID
INNER JOIN OWNS OW2 ON C.ID = OW2.OWNER_ID
INNER JOIN AIRPLANE A2 ON OW2.AIRPLANE_RegNum = A2.Reg#
WHERE PT.Model = a2.OF_TYPE
AND OW2.Pdate >= DATEADD(month, -1, GETDATE())
AND OW.Pdate >= DATEADD(month, -1, GETDATE())