/*------Question 23------*/
SELECT OWNER.Name, COUNT(*) as Total_Planes
FROM OWNER
INNER JOIN OWNS ON OWNER.ID = OWNS.OWNER_ID
INNER JOIN AIRPLANE ON OWNS.AIRPLANE_RegNum = AIRPLANE.Reg#
GROUP BY OWNER.Name;