/*------Question 6------*/
SELECT TOP 5 E.ID, E.Name, SUM(S.Hours) AS TotalHours
FROM EMPLOYEE AS E 
JOIN MAINTAIN AS M ON E.ID = m.EMPLOYEE_ID
JOIN SERVICE AS S ON M.SERVICE_ID = S.ID
GROUP BY E.ID, E.Name
ORDER BY TotalHours DESC
