/*------Question 7------*/
SELECT AIRPLANE.Reg#, PLANE_TYPE.Model
FROM AIRPLANE
INNER JOIN PLANE_TYPE ON AIRPLANE.OF_TYPE = PLANE_TYPE.Model
INNER JOIN MAINTAIN ON AIRPLANE.Reg# = MAINTAIN.SERVICE_ID
INNER JOIN SERVICE ON MAINTAIN.SERVICE_ID = SERVICE.ID
WHERE SERVICE.Date >= DATEADD(day, -7, GETDATE());
